---
- name: Install for Nagios on Ubuntu
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - build-essential
      - libgd-dev
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install for Nagios on CentOS
  yum:
    name:
      - httpd
      - php
      - gcc
      - glibc-devel
      - gd-devel
      - make
    state: latest
  when: ansible_distribution == "CentOS"

